-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.course
(
    course_id integer NOT NULL,
    course_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    credits integer,
    CONSTRAINT course_pkey PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public.department
(
    dept_id integer NOT NULL DEFAULT nextval('department_dept_id_seq'::regclass),
    dept_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT department_pkey PRIMARY KEY (dept_id),
    CONSTRAINT department_dept_name_key UNIQUE (dept_name)
);

CREATE TABLE IF NOT EXISTS public.enrollment
(
    rollno integer NOT NULL,
    course_id integer NOT NULL,
    CONSTRAINT enrollment_pkey PRIMARY KEY (rollno, course_id)
);

CREATE TABLE IF NOT EXISTS public.student
(
    rollno integer NOT NULL,
    s_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    graduation_percentage numeric(5, 2),
    CONSTRAINT student_pkey PRIMARY KEY (rollno)
);

CREATE TABLE IF NOT EXISTS public.student_department
(
    rollno integer NOT NULL,
    dept_id integer,
    CONSTRAINT student_department_pkey PRIMARY KEY (rollno)
);

ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.course (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enrollment
    ADD CONSTRAINT enrollment_rollno_fkey FOREIGN KEY (rollno)
    REFERENCES public.student (rollno) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.student_department
    ADD CONSTRAINT student_department_dept_id_fkey FOREIGN KEY (dept_id)
    REFERENCES public.department (dept_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.student_department
    ADD CONSTRAINT student_department_rollno_fkey FOREIGN KEY (rollno)
    REFERENCES public.student (rollno) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS student_department_pkey
    ON public.student_department(rollno);

END;